"""users provider unique, user_interests unique 제약 추가

Revision ID: 1dd57a123049
Revises: b32f1a2c1781
Create Date: 2026-07-04 07:51:49.918353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dd57a123049'
down_revision: Union[str, None] = 'b32f1a2c1781'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_interests_user_id_type_value', 'user_interests', ['user_id', 'type', 'value'])
    op.create_unique_constraint('uq_users_provider_provider_id', 'users', ['provider', 'provider_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_users_provider_provider_id', 'users', type_='unique')
    op.drop_constraint('uq_user_interests_user_id_type_value', 'user_interests', type_='unique')
    # ### end Alembic commands ###
