"""init

Revision ID: a395b8e042c1
Revises: 
Create Date: 2026-07-01 07:04:50.617144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a395b8e042c1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('daily_briefings', 'top_issue_ids',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.drop_constraint('daily_briefings_briefing_date_time_slot_key', 'daily_briefings', type_='unique')
    op.drop_index('idx_daily_briefings_date', table_name='daily_briefings')
    op.create_index(op.f('ix_daily_briefings_briefing_date'), 'daily_briefings', ['briefing_date'], unique=False)
    op.drop_index('idx_guest_interests_session_token', table_name='guest_interests')
    op.create_index(op.f('ix_guest_interests_session_token'), 'guest_interests', ['session_token'], unique=False)
    op.alter_column('interest_embeddings', 'embedding',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.drop_constraint('interest_embeddings_owner_type_owner_ref_id_keyword_key', 'interest_embeddings', type_='unique')
    op.alter_column('issue_clusters', 'related_stock_codes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.drop_index('idx_issue_clusters_active_date', table_name='issue_clusters')
    op.drop_index('idx_issue_clusters_category', table_name='issue_clusters')
    op.alter_column('news_embeddings', 'embedding',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.drop_constraint('news_embeddings_article_id_key', 'news_embeddings', type_='unique')
    op.drop_index('idx_schedules_date', table_name='schedules')
    op.create_index(op.f('ix_schedules_schedule_date'), 'schedules', ['schedule_date'], unique=False)
    op.drop_index('idx_shared_briefings_token', table_name='shared_briefings')
    op.drop_constraint('shared_briefings_share_token_key', 'shared_briefings', type_='unique')
    op.create_index(op.f('ix_shared_briefings_share_token'), 'shared_briefings', ['share_token'], unique=True)
    op.drop_index('idx_stocks_name', table_name='stocks')
    op.drop_constraint('stocks_code_key', 'stocks', type_='unique')
    op.create_index(op.f('ix_stocks_code'), 'stocks', ['code'], unique=True)
    op.create_index(op.f('ix_stocks_name'), 'stocks', ['name'], unique=False)
    op.alter_column('user_briefings', 'matched_issue_ids',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.drop_index('idx_user_briefings_date', table_name='user_briefings')
    op.drop_constraint('user_briefings_user_id_briefing_date_time_slot_key', 'user_briefings', type_='unique')
    op.create_index(op.f('ix_user_briefings_briefing_date'), 'user_briefings', ['briefing_date'], unique=False)
    op.drop_constraint('user_interests_user_id_type_value_key', 'user_interests', type_='unique')
    op.drop_constraint('users_provider_provider_id_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_provider_provider_id_key', 'users', ['provider', 'provider_id'])
    op.create_unique_constraint('user_interests_user_id_type_value_key', 'user_interests', ['user_id', 'type', 'value'])
    op.drop_index(op.f('ix_user_briefings_briefing_date'), table_name='user_briefings')
    op.create_unique_constraint('user_briefings_user_id_briefing_date_time_slot_key', 'user_briefings', ['user_id', 'briefing_date', 'time_slot'])
    op.create_index('idx_user_briefings_date', 'user_briefings', ['briefing_date'], unique=False)
    op.alter_column('user_briefings', 'matched_issue_ids',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.drop_index(op.f('ix_stocks_name'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_code'), table_name='stocks')
    op.create_unique_constraint('stocks_code_key', 'stocks', ['code'])
    op.create_index('idx_stocks_name', 'stocks', ['name'], unique=False)
    op.drop_index(op.f('ix_shared_briefings_share_token'), table_name='shared_briefings')
    op.create_unique_constraint('shared_briefings_share_token_key', 'shared_briefings', ['share_token'])
    op.create_index('idx_shared_briefings_token', 'shared_briefings', ['share_token'], unique=False)
    op.drop_index(op.f('ix_schedules_schedule_date'), table_name='schedules')
    op.create_index('idx_schedules_date', 'schedules', ['schedule_date'], unique=False)
    op.create_unique_constraint('news_embeddings_article_id_key', 'news_embeddings', ['article_id'])
    op.alter_column('news_embeddings', 'embedding',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.create_index('idx_issue_clusters_category', 'issue_clusters', ['category'], unique=False)
    op.create_index('idx_issue_clusters_active_date', 'issue_clusters', ['is_active', 'created_at'], unique=False)
    op.alter_column('issue_clusters', 'related_stock_codes',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.create_unique_constraint('interest_embeddings_owner_type_owner_ref_id_keyword_key', 'interest_embeddings', ['owner_type', 'owner_ref_id', 'keyword'])
    op.alter_column('interest_embeddings', 'embedding',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_index(op.f('ix_guest_interests_session_token'), table_name='guest_interests')
    op.create_index('idx_guest_interests_session_token', 'guest_interests', ['session_token'], unique=False)
    op.drop_index(op.f('ix_daily_briefings_briefing_date'), table_name='daily_briefings')
    op.create_index('idx_daily_briefings_date', 'daily_briefings', ['briefing_date'], unique=False)
    op.create_unique_constraint('daily_briefings_briefing_date_time_slot_key', 'daily_briefings', ['briefing_date', 'time_slot'])
    op.alter_column('daily_briefings', 'top_issue_ids',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    # ### end Alembic commands ###
